//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domowienia
    {
        public int IdDomowienia { get; set; }
        public Nullable<int> BiletID { get; set; }
        public Nullable<int> TowarID { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public Nullable<decimal> Cena { get; set; }
    
        public virtual Bilet Bilet { get; set; }
        public virtual Towar Towar { get; set; }
    }
}
