//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        public int IdFaktury { get; set; }
        public bool CzyZatwierdzona { get; set; }
        public string Numer { get; set; }
        public System.DateTime DataWystawienia { get; set; }
        public int IdKontrahenta { get; set; }
        public System.DateTime TerminPlatnosci { get; set; }
        public int IdSposobuPlatnosci { get; set; }
        public Nullable<int> DostawcaID { get; set; }
    
        public virtual Kontrahent Kontrahent { get; set; }
        public virtual Dostawca Dostawca { get; set; }
    }
}
