//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinoEntities : DbContext
    {
        public KinoEntities()
            : base("name=KinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilet> Bilet { get; set; }
        public virtual DbSet<Dostawca> Dostawca { get; set; }
        public virtual DbSet<Faktura> Faktura { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Kontrahent> Kontrahent { get; set; }
        public virtual DbSet<Promocja> Promocja { get; set; }
        public virtual DbSet<Recenzja> Recenzja { get; set; }
        public virtual DbSet<Repertuar> Repertuar { get; set; }
        public virtual DbSet<Rezerwacja> Rezerwacja { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Statystyki> Statystyki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Towar> Towar { get; set; }
        public virtual DbSet<Domowienia> Domowienia { get; set; }
        public virtual DbSet<Przerwa> Przerwa { get; set; }
    }
}
