//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocja
    {
        public int PromocjaID { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public decimal Rabat { get; set; }
        public System.DateTime DataRozpoczecia { get; set; }
        public System.DateTime DataZakonczenia { get; set; }
        public Nullable<int> FilmID { get; set; }
        public Nullable<int> BiletID { get; set; }
    
        public virtual Bilet Bilet { get; set; }
        public virtual Film Film { get; set; }
    }
}
