//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacja
    {
        public int RezerwacjaID { get; set; }
        public Nullable<int> KlientID { get; set; }
        public Nullable<int> FilmID { get; set; }
        public System.DateTime DataRezerwacji { get; set; }
        public System.DateTime DataSeansu { get; set; }
        public int LiczbaBiletów { get; set; }
        public string StatusRezerwacji { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Klient Klient { get; set; }
    }
}
